import { APIGatewayEventIncludeConnectionName } from "../src/DTO/http.dto";

export const baseRequest: APIGatewayEventIncludeConnectionName = {
  body: "",
  headers: { Origin: "https://joog-lim.info" },
  multiValueHeaders: {},
  httpMethod: "",
  isBase64Encoded: false,
  path: "",
  pathParameters: {},
  queryStringParameters: {},
  multiValueQueryStringParameters: {},
  stageVariables: {},
  requestContext: {
    apiId: "offlineContext_apiId",
    accountId: "offlineContext_accountId",
    authorizer: {},
    protocol: "HTTP/1.1",
    httpMethod: "GET",
    identity: {
      accessKey: null,
      accountId: "offlineContext_accountId",
      apiKey: "offlineContext_apiKey",
      apiKeyId: "offlineContext_apiKeyId",
      caller: "offlineContext_caller",
      clientCert: null,
      cognitoAuthenticationProvider:
        "offlineContext_cognitoAuthenticationProvider",
      cognitoAuthenticationType: "offlineContext_cognitoAuthenticationType",
      cognitoIdentityId: "offlineContext_cognitoIdentityId",
      cognitoIdentityPoolId: "offlineContext_cognitoIdentityPoolId",
      principalOrgId: null,
      sourceIp: "127.0.0.1",
      user: "offlineContext_user",
      userAgent: "PostmanRuntime/7.29.0",
      userArn: "offlineContext_userArn",
    },
    path: "",
    stage: "test",
    requestId: "cl0ucvd640004ekushiif6i0a",
    requestTimeEpoch: 1647483050077,
    resourceId: "offlineContext_resourceId",
    resourcePath: "",
  },
  resource: "",
  connectionName: "connection1",
};
