service: bamboo-apiv3
useDotenv: true

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ap-northeast-2
  stage: apiV3

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
    GatewayResponseDefault5XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: "ApiGatewayRestApi"

functions:
  getKindOfAlgorithmCount:
    handler: src/handler.getAlgorithmCountAtAll
    events:
      - http:
          path: post/count
          method: get
          cors: true

  getAlgorithmRules:
    handler: src/handler.getAlgorithmRules
    events:
      - http:
          path: post/rule
          method: get
          cors: true

  getAlgorithmRulesForWeb:
    handler: src/handler.getAlgorithmRulesForWeb
    events:
      - http:
          path: post/rule/web
          method: get
          cors: true

  getAlgorithmList:
    handler: src/handler.getAlgorithmList
    events:
      - http:
          path: post/Algorithm-list
          method: get
          cors: true

  getAlgorithmPage:
    handler: src/handler.getAlgorithmListAtPages
    events:
      - http:
          path: post/Algorithm-page
          method: get
          cors: true

  createAlgorithm:
    handler: src/handler.wirteAlgorithm
    events:
      - http:
          path: post/create
          method: post
          cors: true

  deleteAlgorithm:
    handler: src/handler.deleteAlgorithm
    events:
      - http:
          path: post/{id}
          method: delete
          cors: true

  changeStatusAlgorithm:
    handler: src/handler.setAlgorithmStatus
    events:
      - http:
          path: post/{id}/status
          method: patch
          cors: true

  modifyAlgorithm:
    handler: src/handler.modifyAlogirithemContent
    events:
      - http:
          path: post/{id}/modify
          method: patch
          cors: true

  reportAlgorithm:
    handler: src/handler.reportAlgorithm
    events:
      - http:
          path: post/{id}/report
          method: patch
          cors: true

  auth:
    handler: src/handler.authAdmin
    events:
      - http:
          path: auth
          method: post
          cors: true
  verify:
    handler: src/handler.getVerifyQuestion
    events:
      - http:
          path: verify
          method: get
          cors: true
  addVerify:
    handler: src/handler.addVerifyQuestion
    events:
      - http:
          path: verify
          method: post
          cors: true
  login:
    handler: src/handler.login
    events:
      - http:
          path: login
          method: post
          cors: true
  logOut:
    handler: src/handler.logOut
    events:
      - http:
          path: logout
          method: delete
          cors: true
  addLeaf:
    handler: src/handler.addLeaf
    events:
      - http:
          path: leaf
          method: post
          cors: true

  removeLeaf:
    handler: src/handler.removeLeaf
    events:
      - http:
          path: leaf
          method: delete
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  dotenv:
    required:
      env:
        - DISCORD_ACCEPTED_WEBHOOK
        - DISCORD_REPORT_WEBHOOK
        - DISCORD_MANAGEMENT_WEBHOOK
        - DISCORD_ABOUT_DELETE_WEBHOOK
        - ADMIN_PASSWORD
